[\#1544 PR](https://github.com/rear/rear/pull/1544) `merged`: \#1523 Netbackup agents not automatically started
===============================================================================================================

**Labels**: `enhancement`, `fixed / solved / done`, `external tool`

#### <img src="https://avatars.githubusercontent.com/u/1163635?u=36b5e32e1dd55f1ce77cad431a5683fce40a7934&v=4" width="50">[rmetrich](https://github.com/rmetrich) opened issue at [2017-10-25 13:22](https://github.com/rear/rear/pull/1544):

When using NetBackup 7 for ReaR backup (BACKUP=NBU in
/etc/rear/local.conf), the NetBackup initscript (/etc/init.d/netbackup)
is automatically added to the ReaR rescue image as
/etc/scripts/system-setup.d/90-netbackup.sh.

Upon recovery, the agent is *not* started automatically.  
Also the /etc/scripts/system-setup aborts immediately after sourcing
NetBackup initscript, causing auto-recovery to not work.

The root cause is /etc/scripts/system-setup **sourcing** initscripts,
instead of executing them.  
This is OK for other internal scripts, but not for 3rd-party initscripts
ReaR doesn't control.  
In particular, netbackup executes "exit XX" at its end, causing
/etc/scripts/system-setup to exit.

Suggested fix is to modify
/usr/share/rear/rescue/NBU/default/450\_prepare\_netbackup.sh so that
the "/etc/scripts/system-setup.d/netbackup" script runs in a sub-shell,
as shown below:

-   /etc/init.d/netbackup is copied as
    /etc/scripts/system-setup.d/netbackup.real
-   /etc/scripts/system-setup.d/90-netbackup.sh is created to
    encapsulate /etc/scripts/system-setup.d/netbackup.real execution in
    a sub-shell

#### <img src="https://avatars.githubusercontent.com/u/1788608?u=925fc54e2ce01551392622446ece427f51e2f0ce&v=4" width="50">[jsmeix](https://github.com/jsmeix) commented at [2017-10-26 12:03](https://github.com/rear/rear/pull/1544#issuecomment-339643861):

@gdha could you have a look here if time permits  
because you also had a look at
[https://github.com/rear/rear/issues/1523](https://github.com/rear/rear/issues/1523)

#### <img src="https://avatars.githubusercontent.com/u/1788608?u=925fc54e2ce01551392622446ece427f51e2f0ce&v=4" width="50">[jsmeix](https://github.com/jsmeix) commented at [2017-10-26 12:06](https://github.com/rear/rear/pull/1544#issuecomment-339644485):

@pdanek could you review this pull request because  
you submitted
[https://github.com/rear/rear/issues/1523](https://github.com/rear/rear/issues/1523)

#### <img src="https://avatars.githubusercontent.com/u/1163635?u=36b5e32e1dd55f1ce77cad431a5683fce40a7934&v=4" width="50">[rmetrich](https://github.com/rmetrich) commented at [2017-11-30 08:57](https://github.com/rear/rear/pull/1544#issuecomment-348123543):

I got confirmation that, along with fix for \#1609 (PR \#1610), the
NetBackup daemons are now up and running at boot.

#### <img src="https://avatars.githubusercontent.com/u/19947508?v=4" width="50">[pdanek](https://github.com/pdanek) commented at [2017-11-30 09:10](https://github.com/rear/rear/pull/1544#issuecomment-348126702):

Hello guys,

Apologies for late response.

I was in touch with Red Hat Support during last few weeks to resolve
this  
issue.  
They finally fixed this and we have funtional RPM for RHEL7 now.

Perhaps they will provide this back to upstream, but apologies if
double  
work was done.  
I requested information what was the exact cause of the issue, but not  
provided yet.

Best Wishes,  
Peter Danek

On Thu, Nov 30, 2017 at 9:57 AM, Renaud Métrich
<notifications@github.com>  
wrote:

> I got confirmation that, along with fix for \#1609  
> [https://github.com/rear/rear/issues/1609](https://github.com/rear/rear/issues/1609)
> (PR \#1610  
> [https://github.com/rear/rear/pull/1610](https://github.com/rear/rear/pull/1610)),
> the NetBackup daemons are now  
> up and running at boot.
>
> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, view it on GitHub  
> [https://github.com/rear/rear/pull/1544\#issuecomment-348123543](https://github.com/rear/rear/pull/1544#issuecomment-348123543),
> or mute  
> the thread  
> [https://github.com/notifications/unsubscribe-auth/ATBf9BcMN9hkxwEY-SslI1ZMiBBNFNuWks5s7m36gaJpZM4QF\_hd](https://github.com/notifications/unsubscribe-auth/ATBf9BcMN9hkxwEY-SslI1ZMiBBNFNuWks5s7m36gaJpZM4QF_hd)  
> .

#### <img src="https://avatars.githubusercontent.com/u/1163635?u=36b5e32e1dd55f1ce77cad431a5683fce40a7934&v=4" width="50">[rmetrich](https://github.com/rmetrich) commented at [2017-11-30 09:17](https://github.com/rear/rear/pull/1544#issuecomment-348128490):

Hello Peter @pdanek , I filed PR \#1610 to fix upstream rear.

#### <img src="https://avatars.githubusercontent.com/u/19947508?v=4" width="50">[pdanek](https://github.com/pdanek) commented at [2017-11-30 09:31](https://github.com/rear/rear/pull/1544#issuecomment-348131892):

Oh I see that now.

Thanks Renaud.

On Thu, Nov 30, 2017 at 10:17 AM, Renaud Métrich
<notifications@github.com>  
wrote:

> Hello Peter @pdanek
> [https://github.com/pdanek](https://github.com/pdanek) , I filed PR
> \#1610  
> [https://github.com/rear/rear/pull/1610](https://github.com/rear/rear/pull/1610)
> to fix upstream rear.
>
> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, view it on GitHub  
> [https://github.com/rear/rear/pull/1544\#issuecomment-348128490](https://github.com/rear/rear/pull/1544#issuecomment-348128490),
> or mute  
> the thread  
> [https://github.com/notifications/unsubscribe-auth/ATBf9NLNSeMsNGc-6Aj6R9voFhmQwxIGks5s7nKrgaJpZM4QF\_hd](https://github.com/notifications/unsubscribe-auth/ATBf9NLNSeMsNGc-6Aj6R9voFhmQwxIGks5s7nKrgaJpZM4QF_hd)  
> .

------------------------------------------------------------------------

\[Export of Github issue for
[rear/rear](https://github.com/rear/rear).\]
